name: Metrics
on:
  schedule:
    - cron: "0 0 * * *"   # Ejecuta cada día a medianoche
  workflow_dispatch:       # Permite ejecución manual

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: ferogv
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/Mexico_City
          filename: metrics.svg

      - name: Commit and push metrics
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add metrics.svg
          git commit -m "Update metrics"
          git push
